name: Run Tests

on:
  workflow_call:
    inputs:
      install_string:
        required: True
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ##############################################
      # Skip caching if using a local runner.
      - uses: actions/setup-python@v4
        if: ${{ !env.ACT }}
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - uses: actions/setup-python@v4
        if: ${{ env.ACT }}
        with:
          python-version: '3.10'
      ##############################################
      - name: Install CPU version of torch.
        run: pip install torch==1.11.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Install the torch-geometric.
        run: pip install pyg_lib==0.2.0 torch_scatter==2.0.9 torch_sparse==0.6.16 torch_cluster==1.6.0 torch_spline_conv==1.2.1 -f https://data.pyg.org/whl/torch-1.11.0+cpu.html

      - name: Install package
        run: pip install "${{ inputs.install_string }}"

      - name: Code Quality
        run: python -m black src/ tests/ --check

      - name: MyPy Typechecking
        run: python -m mypy src/ tests/

      # Run tests.
      - name: Test with pytest
        run: python -m pytest
